<?php
/**
 * ProductInventoryApi
 * PHP version 5
 *
 * @category Class
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Advantage Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Advantage Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Advantage\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Advantage\Client\ApiException;
use Advantage\Client\Configuration;
use Advantage\Client\HeaderSelector;
use Advantage\Client\ObjectSerializer;

/**
 * ProductInventoryApi Class Doc Comment
 *
 * @category Class
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductInventoryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation productInventoryCreateInventoryAdjustment
     *
     * @param  string $item_number item_number (required)
     * @param  string $warehouse_number warehouse_number (required)
     * @param  \Advantage\Client\Model\InventoryAdjustmentRequest $request request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\InventoryAdjustmentResponse
     */
    public function productInventoryCreateInventoryAdjustment($item_number, $warehouse_number, $request)
    {
        list($response) = $this->productInventoryCreateInventoryAdjustmentWithHttpInfo($item_number, $warehouse_number, $request);
        return $response;
    }

    /**
     * Operation productInventoryCreateInventoryAdjustmentWithHttpInfo
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\InventoryAdjustmentRequest $request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\InventoryAdjustmentResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryCreateInventoryAdjustmentWithHttpInfo($item_number, $warehouse_number, $request)
    {
        $returnType = '\Advantage\Client\Model\InventoryAdjustmentResponse';
        $request = $this->productInventoryCreateInventoryAdjustmentRequest($item_number, $warehouse_number, $request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\InventoryAdjustmentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryCreateInventoryAdjustmentAsync
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\InventoryAdjustmentRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateInventoryAdjustmentAsync($item_number, $warehouse_number, $request)
    {
        return $this->productInventoryCreateInventoryAdjustmentAsyncWithHttpInfo($item_number, $warehouse_number, $request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryCreateInventoryAdjustmentAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\InventoryAdjustmentRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateInventoryAdjustmentAsyncWithHttpInfo($item_number, $warehouse_number, $request)
    {
        $returnType = '\Advantage\Client\Model\InventoryAdjustmentResponse';
        $request = $this->productInventoryCreateInventoryAdjustmentRequest($item_number, $warehouse_number, $request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryCreateInventoryAdjustment'
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\InventoryAdjustmentRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryCreateInventoryAdjustmentRequest($item_number, $warehouse_number, $request)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryCreateInventoryAdjustment'
            );
        }
        // verify the required parameter 'warehouse_number' is set
        if ($warehouse_number === null || (is_array($warehouse_number) && count($warehouse_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouse_number when calling productInventoryCreateInventoryAdjustment'
            );
        }
        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling productInventoryCreateInventoryAdjustment'
            );
        }

        $resourcePath = '/products/{itemNumber}/warehouses/{warehouseNumber}/inventory-adjustments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }
        // path params
        if ($warehouse_number !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseNumber' . '}',
                ObjectSerializer::toPathValue($warehouse_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($request)) {
            $_tempBody = $request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                ['application/json', 'text/json', 'text/html', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation productInventoryCreateItemInventoryReceipt
     *
     * @param  string $item_number item_number (required)
     * @param  string $warehouse_number warehouse_number (required)
     * @param  \Advantage\Client\Model\ReceiptItemInventoryReceiptCreateRequest $request request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\ItemInventoryReceiptResponse
     */
    public function productInventoryCreateItemInventoryReceipt($item_number, $warehouse_number, $request)
    {
        list($response) = $this->productInventoryCreateItemInventoryReceiptWithHttpInfo($item_number, $warehouse_number, $request);
        return $response;
    }

    /**
     * Operation productInventoryCreateItemInventoryReceiptWithHttpInfo
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\ReceiptItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\ItemInventoryReceiptResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryCreateItemInventoryReceiptWithHttpInfo($item_number, $warehouse_number, $request)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceiptResponse';
        $request = $this->productInventoryCreateItemInventoryReceiptRequest($item_number, $warehouse_number, $request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\ItemInventoryReceiptResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryCreateItemInventoryReceiptAsync
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\ReceiptItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateItemInventoryReceiptAsync($item_number, $warehouse_number, $request)
    {
        return $this->productInventoryCreateItemInventoryReceiptAsyncWithHttpInfo($item_number, $warehouse_number, $request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryCreateItemInventoryReceiptAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\ReceiptItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateItemInventoryReceiptAsyncWithHttpInfo($item_number, $warehouse_number, $request)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceiptResponse';
        $request = $this->productInventoryCreateItemInventoryReceiptRequest($item_number, $warehouse_number, $request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryCreateItemInventoryReceipt'
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  \Advantage\Client\Model\ReceiptItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryCreateItemInventoryReceiptRequest($item_number, $warehouse_number, $request)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryCreateItemInventoryReceipt'
            );
        }
        // verify the required parameter 'warehouse_number' is set
        if ($warehouse_number === null || (is_array($warehouse_number) && count($warehouse_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouse_number when calling productInventoryCreateItemInventoryReceipt'
            );
        }
        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling productInventoryCreateItemInventoryReceipt'
            );
        }

        $resourcePath = '/products/{itemNumber}/warehouses/{warehouseNumber}/inventory-receipts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }
        // path params
        if ($warehouse_number !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseNumber' . '}',
                ObjectSerializer::toPathValue($warehouse_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($request)) {
            $_tempBody = $request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                ['application/json', 'text/json', 'text/html', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation productInventoryCreateItemInventoryReceipt_0
     *
     * @param  string $item_number item_number (required)
     * @param  string $warehouse_number warehouse_number (required)
     * @param  string $purchase_order_number purchase_order_number (required)
     * @param  \Advantage\Client\Model\PurchaseOrderItemInventoryReceiptCreateRequest $request request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\ItemInventoryReceiptResponse
     */
    public function productInventoryCreateItemInventoryReceipt_0($item_number, $warehouse_number, $purchase_order_number, $request)
    {
        list($response) = $this->productInventoryCreateItemInventoryReceipt_0WithHttpInfo($item_number, $warehouse_number, $purchase_order_number, $request);
        return $response;
    }

    /**
     * Operation productInventoryCreateItemInventoryReceipt_0WithHttpInfo
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $purchase_order_number (required)
     * @param  \Advantage\Client\Model\PurchaseOrderItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\ItemInventoryReceiptResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryCreateItemInventoryReceipt_0WithHttpInfo($item_number, $warehouse_number, $purchase_order_number, $request)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceiptResponse';
        $request = $this->productInventoryCreateItemInventoryReceipt_0Request($item_number, $warehouse_number, $purchase_order_number, $request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\ItemInventoryReceiptResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryCreateItemInventoryReceipt_0Async
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $purchase_order_number (required)
     * @param  \Advantage\Client\Model\PurchaseOrderItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateItemInventoryReceipt_0Async($item_number, $warehouse_number, $purchase_order_number, $request)
    {
        return $this->productInventoryCreateItemInventoryReceipt_0AsyncWithHttpInfo($item_number, $warehouse_number, $purchase_order_number, $request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryCreateItemInventoryReceipt_0AsyncWithHttpInfo
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $purchase_order_number (required)
     * @param  \Advantage\Client\Model\PurchaseOrderItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryCreateItemInventoryReceipt_0AsyncWithHttpInfo($item_number, $warehouse_number, $purchase_order_number, $request)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceiptResponse';
        $request = $this->productInventoryCreateItemInventoryReceipt_0Request($item_number, $warehouse_number, $purchase_order_number, $request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryCreateItemInventoryReceipt_0'
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $purchase_order_number (required)
     * @param  \Advantage\Client\Model\PurchaseOrderItemInventoryReceiptCreateRequest $request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryCreateItemInventoryReceipt_0Request($item_number, $warehouse_number, $purchase_order_number, $request)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryCreateItemInventoryReceipt_0'
            );
        }
        // verify the required parameter 'warehouse_number' is set
        if ($warehouse_number === null || (is_array($warehouse_number) && count($warehouse_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouse_number when calling productInventoryCreateItemInventoryReceipt_0'
            );
        }
        // verify the required parameter 'purchase_order_number' is set
        if ($purchase_order_number === null || (is_array($purchase_order_number) && count($purchase_order_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $purchase_order_number when calling productInventoryCreateItemInventoryReceipt_0'
            );
        }
        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling productInventoryCreateItemInventoryReceipt_0'
            );
        }

        $resourcePath = '/products/{itemNumber}/warehouses/{warehouseNumber}/purchase-orders/{purchaseOrderNumber}/inventory-receipts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }
        // path params
        if ($warehouse_number !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseNumber' . '}',
                ObjectSerializer::toPathValue($warehouse_number),
                $resourcePath
            );
        }
        // path params
        if ($purchase_order_number !== null) {
            $resourcePath = str_replace(
                '{' . 'purchaseOrderNumber' . '}',
                ObjectSerializer::toPathValue($purchase_order_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($request)) {
            $_tempBody = $request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                ['application/json', 'text/json', 'text/html', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation productInventoryGetInventory
     *
     * Get the inventory status for a given product.
     *
     * @param  string $item_number The item number of the product of interest. (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\ProductInventory
     */
    public function productInventoryGetInventory($item_number)
    {
        list($response) = $this->productInventoryGetInventoryWithHttpInfo($item_number);
        return $response;
    }

    /**
     * Operation productInventoryGetInventoryWithHttpInfo
     *
     * Get the inventory status for a given product.
     *
     * @param  string $item_number The item number of the product of interest. (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\ProductInventory, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryGetInventoryWithHttpInfo($item_number)
    {
        $returnType = '\Advantage\Client\Model\ProductInventory';
        $request = $this->productInventoryGetInventoryRequest($item_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\ProductInventory',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryGetInventoryAsync
     *
     * Get the inventory status for a given product.
     *
     * @param  string $item_number The item number of the product of interest. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetInventoryAsync($item_number)
    {
        return $this->productInventoryGetInventoryAsyncWithHttpInfo($item_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryGetInventoryAsyncWithHttpInfo
     *
     * Get the inventory status for a given product.
     *
     * @param  string $item_number The item number of the product of interest. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetInventoryAsyncWithHttpInfo($item_number)
    {
        $returnType = '\Advantage\Client\Model\ProductInventory';
        $request = $this->productInventoryGetInventoryRequest($item_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryGetInventory'
     *
     * @param  string $item_number The item number of the product of interest. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryGetInventoryRequest($item_number)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryGetInventory'
            );
        }

        $resourcePath = '/products/{itemNumber}/inventory-status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation productInventoryGetInventoryAdjustment
     *
     * @param  string $item_number item_number (required)
     * @param  string $warehouse_number warehouse_number (required)
     * @param  string $bin bin (required)
     * @param  string $transaction_number transaction_number (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\InventoryAdjustment
     */
    public function productInventoryGetInventoryAdjustment($item_number, $warehouse_number, $bin, $transaction_number)
    {
        list($response) = $this->productInventoryGetInventoryAdjustmentWithHttpInfo($item_number, $warehouse_number, $bin, $transaction_number);
        return $response;
    }

    /**
     * Operation productInventoryGetInventoryAdjustmentWithHttpInfo
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $bin (required)
     * @param  string $transaction_number (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\InventoryAdjustment, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryGetInventoryAdjustmentWithHttpInfo($item_number, $warehouse_number, $bin, $transaction_number)
    {
        $returnType = '\Advantage\Client\Model\InventoryAdjustment';
        $request = $this->productInventoryGetInventoryAdjustmentRequest($item_number, $warehouse_number, $bin, $transaction_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\InventoryAdjustment',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryGetInventoryAdjustmentAsync
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $bin (required)
     * @param  string $transaction_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetInventoryAdjustmentAsync($item_number, $warehouse_number, $bin, $transaction_number)
    {
        return $this->productInventoryGetInventoryAdjustmentAsyncWithHttpInfo($item_number, $warehouse_number, $bin, $transaction_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryGetInventoryAdjustmentAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $bin (required)
     * @param  string $transaction_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetInventoryAdjustmentAsyncWithHttpInfo($item_number, $warehouse_number, $bin, $transaction_number)
    {
        $returnType = '\Advantage\Client\Model\InventoryAdjustment';
        $request = $this->productInventoryGetInventoryAdjustmentRequest($item_number, $warehouse_number, $bin, $transaction_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryGetInventoryAdjustment'
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  string $bin (required)
     * @param  string $transaction_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryGetInventoryAdjustmentRequest($item_number, $warehouse_number, $bin, $transaction_number)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryGetInventoryAdjustment'
            );
        }
        // verify the required parameter 'warehouse_number' is set
        if ($warehouse_number === null || (is_array($warehouse_number) && count($warehouse_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouse_number when calling productInventoryGetInventoryAdjustment'
            );
        }
        // verify the required parameter 'bin' is set
        if ($bin === null || (is_array($bin) && count($bin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bin when calling productInventoryGetInventoryAdjustment'
            );
        }
        // verify the required parameter 'transaction_number' is set
        if ($transaction_number === null || (is_array($transaction_number) && count($transaction_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $transaction_number when calling productInventoryGetInventoryAdjustment'
            );
        }

        $resourcePath = '/products/{itemNumber}/warehouses/{warehouseNumber}/bins/{bin}/inventory-adjustments/{transactionNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }
        // path params
        if ($warehouse_number !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseNumber' . '}',
                ObjectSerializer::toPathValue($warehouse_number),
                $resourcePath
            );
        }
        // path params
        if ($bin !== null) {
            $resourcePath = str_replace(
                '{' . 'bin' . '}',
                ObjectSerializer::toPathValue($bin),
                $resourcePath
            );
        }
        // path params
        if ($transaction_number !== null) {
            $resourcePath = str_replace(
                '{' . 'transactionNumber' . '}',
                ObjectSerializer::toPathValue($transaction_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation productInventoryGetItemInventoryReceipt
     *
     * @param  string $item_number item_number (required)
     * @param  string $warehouse_number warehouse_number (required)
     * @param  double $receiving_number receiving_number (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\ItemInventoryReceipt
     */
    public function productInventoryGetItemInventoryReceipt($item_number, $warehouse_number, $receiving_number)
    {
        list($response) = $this->productInventoryGetItemInventoryReceiptWithHttpInfo($item_number, $warehouse_number, $receiving_number);
        return $response;
    }

    /**
     * Operation productInventoryGetItemInventoryReceiptWithHttpInfo
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  double $receiving_number (required)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\ItemInventoryReceipt, HTTP status code, HTTP response headers (array of strings)
     */
    public function productInventoryGetItemInventoryReceiptWithHttpInfo($item_number, $warehouse_number, $receiving_number)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceipt';
        $request = $this->productInventoryGetItemInventoryReceiptRequest($item_number, $warehouse_number, $receiving_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\ItemInventoryReceipt',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation productInventoryGetItemInventoryReceiptAsync
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  double $receiving_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetItemInventoryReceiptAsync($item_number, $warehouse_number, $receiving_number)
    {
        return $this->productInventoryGetItemInventoryReceiptAsyncWithHttpInfo($item_number, $warehouse_number, $receiving_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation productInventoryGetItemInventoryReceiptAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  double $receiving_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function productInventoryGetItemInventoryReceiptAsyncWithHttpInfo($item_number, $warehouse_number, $receiving_number)
    {
        $returnType = '\Advantage\Client\Model\ItemInventoryReceipt';
        $request = $this->productInventoryGetItemInventoryReceiptRequest($item_number, $warehouse_number, $receiving_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'productInventoryGetItemInventoryReceipt'
     *
     * @param  string $item_number (required)
     * @param  string $warehouse_number (required)
     * @param  double $receiving_number (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function productInventoryGetItemInventoryReceiptRequest($item_number, $warehouse_number, $receiving_number)
    {
        // verify the required parameter 'item_number' is set
        if ($item_number === null || (is_array($item_number) && count($item_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_number when calling productInventoryGetItemInventoryReceipt'
            );
        }
        // verify the required parameter 'warehouse_number' is set
        if ($warehouse_number === null || (is_array($warehouse_number) && count($warehouse_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouse_number when calling productInventoryGetItemInventoryReceipt'
            );
        }
        // verify the required parameter 'receiving_number' is set
        if ($receiving_number === null || (is_array($receiving_number) && count($receiving_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $receiving_number when calling productInventoryGetItemInventoryReceipt'
            );
        }

        $resourcePath = '/products/{itemNumber}/warehouses/{warehouseNumber}/inventory-receipts/{receivingNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($item_number !== null) {
            $resourcePath = str_replace(
                '{' . 'itemNumber' . '}',
                ObjectSerializer::toPathValue($item_number),
                $resourcePath
            );
        }
        // path params
        if ($warehouse_number !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseNumber' . '}',
                ObjectSerializer::toPathValue($warehouse_number),
                $resourcePath
            );
        }
        // path params
        if ($receiving_number !== null) {
            $resourcePath = str_replace(
                '{' . 'receivingNumber' . '}',
                ObjectSerializer::toPathValue($receiving_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
