<?php
/**
 * QuestionnaireApi
 * PHP version 5
 *
 * @category Class
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Advantage Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Advantage Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Advantage\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Advantage\Client\ApiException;
use Advantage\Client\Configuration;
use Advantage\Client\HeaderSelector;
use Advantage\Client\ObjectSerializer;

/**
 * QuestionnaireApi Class Doc Comment
 *
 * @category Class
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnaireApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation questionnaireGet
     *
     * Gets the questionnaire.  Some questionnaires will carry forward the customer's previous   responses to use as the defaults when the questionnaire is presented a second time.  This   feature is supported only if you provide the optional profile ID parameter.
     *
     * @param  string $questionnaire_code The questionnaire to return (required)
     * @param  string $profile_id The ID of the profile containing the customer&#39;s previous responses,              e.g. the profile (responses) from the customer&#39;s previous subscription term. (optional)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Advantage\Client\Model\Questionnaire
     */
    public function questionnaireGet($questionnaire_code, $profile_id = null)
    {
        list($response) = $this->questionnaireGetWithHttpInfo($questionnaire_code, $profile_id);
        return $response;
    }

    /**
     * Operation questionnaireGetWithHttpInfo
     *
     * Gets the questionnaire.  Some questionnaires will carry forward the customer's previous   responses to use as the defaults when the questionnaire is presented a second time.  This   feature is supported only if you provide the optional profile ID parameter.
     *
     * @param  string $questionnaire_code The questionnaire to return (required)
     * @param  string $profile_id The ID of the profile containing the customer&#39;s previous responses,              e.g. the profile (responses) from the customer&#39;s previous subscription term. (optional)
     *
     * @throws \Advantage\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Advantage\Client\Model\Questionnaire, HTTP status code, HTTP response headers (array of strings)
     */
    public function questionnaireGetWithHttpInfo($questionnaire_code, $profile_id = null)
    {
        $returnType = '\Advantage\Client\Model\Questionnaire';
        $request = $this->questionnaireGetRequest($questionnaire_code, $profile_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Advantage\Client\Model\Questionnaire',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation questionnaireGetAsync
     *
     * Gets the questionnaire.  Some questionnaires will carry forward the customer's previous   responses to use as the defaults when the questionnaire is presented a second time.  This   feature is supported only if you provide the optional profile ID parameter.
     *
     * @param  string $questionnaire_code The questionnaire to return (required)
     * @param  string $profile_id The ID of the profile containing the customer&#39;s previous responses,              e.g. the profile (responses) from the customer&#39;s previous subscription term. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function questionnaireGetAsync($questionnaire_code, $profile_id = null)
    {
        return $this->questionnaireGetAsyncWithHttpInfo($questionnaire_code, $profile_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation questionnaireGetAsyncWithHttpInfo
     *
     * Gets the questionnaire.  Some questionnaires will carry forward the customer's previous   responses to use as the defaults when the questionnaire is presented a second time.  This   feature is supported only if you provide the optional profile ID parameter.
     *
     * @param  string $questionnaire_code The questionnaire to return (required)
     * @param  string $profile_id The ID of the profile containing the customer&#39;s previous responses,              e.g. the profile (responses) from the customer&#39;s previous subscription term. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function questionnaireGetAsyncWithHttpInfo($questionnaire_code, $profile_id = null)
    {
        $returnType = '\Advantage\Client\Model\Questionnaire';
        $request = $this->questionnaireGetRequest($questionnaire_code, $profile_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'questionnaireGet'
     *
     * @param  string $questionnaire_code The questionnaire to return (required)
     * @param  string $profile_id The ID of the profile containing the customer&#39;s previous responses,              e.g. the profile (responses) from the customer&#39;s previous subscription term. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function questionnaireGetRequest($questionnaire_code, $profile_id = null)
    {
        // verify the required parameter 'questionnaire_code' is set
        if ($questionnaire_code === null || (is_array($questionnaire_code) && count($questionnaire_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $questionnaire_code when calling questionnaireGet'
            );
        }

        $resourcePath = '/questionnaires/{questionnaireCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($profile_id !== null) {
            $queryParams['profileId'] = ObjectSerializer::toQueryValue($profile_id);
        }

        // path params
        if ($questionnaire_code !== null) {
            $resourcePath = str_replace(
                '{' . 'questionnaireCode' . '}',
                ObjectSerializer::toPathValue($questionnaire_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
