<?php
/**
 * AdvantageUserPreferencesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdvantageUserPreferencesTest Class Doc Comment
 *
 * @category    Class
 * @description Model for Preferences for Advantage User
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdvantageUserPreferencesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdvantageUserPreferences"
     */
    public function testAdvantageUserPreferences()
    {
    }

    /**
     * Test attribute "ui_date_format"
     */
    public function testPropertyUiDateFormat()
    {
    }

    /**
     * Test attribute "printer_code"
     */
    public function testPropertyPrinterCode()
    {
    }

    /**
     * Test attribute "printer_form_code"
     */
    public function testPropertyPrinterFormCode()
    {
    }

    /**
     * Test attribute "ui_time_format"
     */
    public function testPropertyUiTimeFormat()
    {
    }
}
