<?php
/**
 * AgreementRenewalOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AgreementRenewalOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Options for renewing an agreement through the Advantage REST API.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgreementRenewalOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AgreementRenewalOptions"
     */
    public function testAgreementRenewalOptions()
    {
    }

    /**
     * Test attribute "promotion_code"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "promotion_choice_code"
     */
    public function testPropertyPromotionChoiceCode()
    {
    }

    /**
     * Test attribute "bill_to"
     */
    public function testPropertyBillTo()
    {
    }

    /**
     * Test attribute "order_by"
     */
    public function testPropertyOrderBy()
    {
    }

    /**
     * Test attribute "access_period_code"
     */
    public function testPropertyAccessPeriodCode()
    {
    }

    /**
     * Test attribute "agreement_type"
     */
    public function testPropertyAgreementType()
    {
    }

    /**
     * Test attribute "purchase_order_number"
     */
    public function testPropertyPurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "copy_points_and_parts"
     */
    public function testPropertyCopyPointsAndParts()
    {
    }

    /**
     * Test attribute "use_previous_term_discount"
     */
    public function testPropertyUsePreviousTermDiscount()
    {
    }

    /**
     * Test attribute "use_customer_discount"
     */
    public function testPropertyUseCustomerDiscount()
    {
    }

    /**
     * Test attribute "new_discount"
     */
    public function testPropertyNewDiscount()
    {
    }

    /**
     * Test attribute "update_with_promotion_defaults"
     */
    public function testPropertyUpdateWithPromotionDefaults()
    {
    }

    /**
     * Test attribute "use_previous_term_renewal_discount"
     */
    public function testPropertyUsePreviousTermRenewalDiscount()
    {
    }

    /**
     * Test attribute "copy_free_days"
     */
    public function testPropertyCopyFreeDays()
    {
    }

    /**
     * Test attribute "copy_extension_days"
     */
    public function testPropertyCopyExtensionDays()
    {
    }

    /**
     * Test attribute "copy_adjustment_days"
     */
    public function testPropertyCopyAdjustmentDays()
    {
    }

    /**
     * Test attribute "copy_grace_days"
     */
    public function testPropertyCopyGraceDays()
    {
    }

    /**
     * Test attribute "autorenew_chain_id"
     */
    public function testPropertyAutorenewChainId()
    {
    }

    /**
     * Test attribute "autorenew_chain_sequence"
     */
    public function testPropertyAutorenewChainSequence()
    {
    }

    /**
     * Test attribute "is_on_approval"
     */
    public function testPropertyIsOnApproval()
    {
    }

    /**
     * Test attribute "agency_reference"
     */
    public function testPropertyAgencyReference()
    {
    }

    /**
     * Test attribute "master_agreement_id"
     */
    public function testPropertyMasterAgreementId()
    {
    }

    /**
     * Test attribute "billing_currency"
     */
    public function testPropertyBillingCurrency()
    {
    }

    /**
     * Test attribute "renewal_price_increase_percent"
     */
    public function testPropertyRenewalPriceIncreasePercent()
    {
    }

    /**
     * Test attribute "max_change_percentage"
     */
    public function testPropertyMaxChangePercentage()
    {
    }

    /**
     * Test attribute "commit_order"
     */
    public function testPropertyCommitOrder()
    {
    }
}
