<?php
/**
 * ControlGroupSubscriptionDefaultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ControlGroupSubscriptionDefaultsTest Class Doc Comment
 *
 * @category    Class
 * @description Subscription Defaults for Control Group Model
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ControlGroupSubscriptionDefaultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ControlGroupSubscriptionDefaults"
     */
    public function testControlGroupSubscriptionDefaults()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "delivery_code"
     */
    public function testPropertyDeliveryCode()
    {
    }

    /**
     * Test attribute "term_length"
     */
    public function testPropertyTermLength()
    {
    }

    /**
     * Test attribute "subscription_class_code"
     */
    public function testPropertySubscriptionClassCode()
    {
    }

    /**
     * Test attribute "postage"
     */
    public function testPropertyPostage()
    {
    }

    /**
     * Test attribute "billing_status_code"
     */
    public function testPropertyBillingStatusCode()
    {
    }

    /**
     * Test attribute "starts"
     */
    public function testPropertyStarts()
    {
    }

    /**
     * Test attribute "renewal_starts"
     */
    public function testPropertyRenewalStarts()
    {
    }

    /**
     * Test attribute "donor_type_code"
     */
    public function testPropertyDonorTypeCode()
    {
    }

    /**
     * Test attribute "subscription_type_code"
     */
    public function testPropertySubscriptionTypeCode()
    {
    }

    /**
     * Test attribute "sales_rep_code"
     */
    public function testPropertySalesRepCode()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "issue_group_code"
     */
    public function testPropertyIssueGroupCode()
    {
    }

    /**
     * Test attribute "free_issues"
     */
    public function testPropertyFreeIssues()
    {
    }

    /**
     * Test attribute "check_for_duplicate_subscriptions"
     */
    public function testPropertyCheckForDuplicateSubscriptions()
    {
    }

    /**
     * Test attribute "edition_code"
     */
    public function testPropertyEditionCode()
    {
    }

    /**
     * Test attribute "override_edition"
     */
    public function testPropertyOverrideEdition()
    {
    }

    /**
     * Test attribute "questionnaire_code"
     */
    public function testPropertyQuestionnaireCode()
    {
    }

    /**
     * Test attribute "referred_by_customer_number"
     */
    public function testPropertyReferredByCustomerNumber()
    {
    }
}
