<?php
/**
 * CustomerCreateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerCreateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Information needed to request the creation of a customer.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerCreateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerCreateRequest"
     */
    public function testCustomerCreateRequest()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "address_standardization_setting"
     */
    public function testPropertyAddressStandardizationSetting()
    {
    }

    /**
     * Test attribute "promote"
     */
    public function testPropertyPromote()
    {
    }

    /**
     * Test attribute "promote_by_partners"
     */
    public function testPropertyPromoteByPartners()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "sex_code"
     */
    public function testPropertySexCode()
    {
    }

    /**
     * Test attribute "customer_type"
     */
    public function testPropertyCustomerType()
    {
    }

    /**
     * Test attribute "change_source"
     */
    public function testPropertyChangeSource()
    {
    }

    /**
     * Test attribute "demographics"
     */
    public function testPropertyDemographics()
    {
    }

    /**
     * Test attribute "block_duplicate_match_level_code"
     */
    public function testPropertyBlockDuplicateMatchLevelCode()
    {
    }

    /**
     * Test attribute "force_create"
     */
    public function testPropertyForceCreate()
    {
    }

    /**
     * Test attribute "is_account"
     */
    public function testPropertyIsAccount()
    {
    }

    /**
     * Test attribute "block_duplicate_match_with_activity"
     */
    public function testPropertyBlockDuplicateMatchWithActivity()
    {
    }
}
