<?php
/**
 * CustomerActivityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerActivityTest Class Doc Comment
 *
 * @category    Class
 * @description Contains all of the information about a Customer Activity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerActivityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerActivity"
     */
    public function testCustomerActivity()
    {
    }

    /**
     * Test attribute "system_name"
     */
    public function testPropertySystemName()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }

    /**
     * Test attribute "term_number"
     */
    public function testPropertyTermNumber()
    {
    }

    /**
     * Test attribute "activity_sequence"
     */
    public function testPropertyActivitySequence()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "address_code"
     */
    public function testPropertyAddressCode()
    {
    }

    /**
     * Test attribute "activity_status"
     */
    public function testPropertyActivityStatus()
    {
    }

    /**
     * Test attribute "status_description"
     */
    public function testPropertyStatusDescription()
    {
    }

    /**
     * Test attribute "sub_reference"
     */
    public function testPropertySubReference()
    {
    }

    /**
     * Test attribute "agreement_id"
     */
    public function testPropertyAgreementId()
    {
    }

    /**
     * Test attribute "customer_po_number"
     */
    public function testPropertyCustomerPoNumber()
    {
    }

    /**
     * Test attribute "owning_organization"
     */
    public function testPropertyOwningOrganization()
    {
    }

    /**
     * Test attribute "original_order_number"
     */
    public function testPropertyOriginalOrderNumber()
    {
    }

    /**
     * Test attribute "promotion_code"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "promotion_choice"
     */
    public function testPropertyPromotionChoice()
    {
    }

    /**
     * Test attribute "billing_status"
     */
    public function testPropertyBillingStatus()
    {
    }

    /**
     * Test attribute "billing_status_description"
     */
    public function testPropertyBillingStatusDescription()
    {
    }

    /**
     * Test attribute "final_expire_date"
     */
    public function testPropertyFinalExpireDate()
    {
    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {
    }

    /**
     * Test attribute "control_group_date"
     */
    public function testPropertyControlGroupDate()
    {
    }

    /**
     * Test attribute "control_group_id"
     */
    public function testPropertyControlGroupId()
    {
    }

    /**
     * Test attribute "membership_organization"
     */
    public function testPropertyMembershipOrganization()
    {
    }

    /**
     * Test attribute "membership_category"
     */
    public function testPropertyMembershipCategory()
    {
    }

    /**
     * Test attribute "circulation_status"
     */
    public function testPropertyCirculationStatus()
    {
    }

    /**
     * Test attribute "circulation_status_description"
     */
    public function testPropertyCirculationStatusDescription()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "remaining_liability"
     */
    public function testPropertyRemainingLiability()
    {
    }
}
