<?php
/**
 * ModificationTrackingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModificationTrackingTest Class Doc Comment
 *
 * @category    Class
 * @description Information that&#39;s used to track modification information
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModificationTrackingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModificationTracking"
     */
    public function testModificationTracking()
    {
    }

    /**
     * Test attribute "is_modification"
     */
    public function testPropertyIsModification()
    {
    }

    /**
     * Test attribute "approval_date"
     */
    public function testPropertyApprovalDate()
    {
    }

    /**
     * Test attribute "base_flag"
     */
    public function testPropertyBaseFlag()
    {
    }

    /**
     * Test attribute "declined_date"
     */
    public function testPropertyDeclinedDate()
    {
    }

    /**
     * Test attribute "decline_reason"
     */
    public function testPropertyDeclineReason()
    {
    }

    /**
     * Test attribute "is_approval_via_email"
     */
    public function testPropertyIsApprovalViaEmail()
    {
    }

    /**
     * Test attribute "is_fixed_cost"
     */
    public function testPropertyIsFixedCost()
    {
    }

    /**
     * Test attribute "modification_status"
     */
    public function testPropertyModificationStatus()
    {
    }

    /**
     * Test attribute "primary_module"
     */
    public function testPropertyPrimaryModule()
    {
    }

    /**
     * Test attribute "retrofit_revision"
     */
    public function testPropertyRetrofitRevision()
    {
    }

    /**
     * Test attribute "specification_date"
     */
    public function testPropertySpecificationDate()
    {
    }

    /**
     * Test attribute "specification_created_by"
     */
    public function testPropertySpecificationCreatedBy()
    {
    }
}
