<?php
/**
 * OrderLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderLineTest Class Doc Comment
 *
 * @category    Class
 * @description Information for a line in an order.   This contains information for order lines of various types (product, subscription, agreement, etc.)  Only properties for the appropriate order line type are populated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderLine"
     */
    public function testOrderLine()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "promotion_code"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "promotion_choice"
     */
    public function testPropertyPromotionChoice()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "is_package_component"
     */
    public function testPropertyIsPackageComponent()
    {
    }

    /**
     * Test attribute "is_association_component"
     */
    public function testPropertyIsAssociationComponent()
    {
    }

    /**
     * Test attribute "is_package_header"
     */
    public function testPropertyIsPackageHeader()
    {
    }

    /**
     * Test attribute "is_premium"
     */
    public function testPropertyIsPremium()
    {
    }

    /**
     * Test attribute "quantity_ordered"
     */
    public function testPropertyQuantityOrdered()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "sales_amount"
     */
    public function testPropertySalesAmount()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "shipping_charges"
     */
    public function testPropertyShippingCharges()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "total_cost"
     */
    public function testPropertyTotalCost()
    {
    }

    /**
     * Test attribute "shipping_charges_ordered"
     */
    public function testPropertyShippingChargesOrdered()
    {
    }

    /**
     * Test attribute "discount_ordered"
     */
    public function testPropertyDiscountOrdered()
    {
    }

    /**
     * Test attribute "tax_ordered"
     */
    public function testPropertyTaxOrdered()
    {
    }

    /**
     * Test attribute "sales_amount_ordered"
     */
    public function testPropertySalesAmountOrdered()
    {
    }

    /**
     * Test attribute "sales_amount_shipped"
     */
    public function testPropertySalesAmountShipped()
    {
    }

    /**
     * Test attribute "total_cost_ordered"
     */
    public function testPropertyTotalCostOrdered()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "package_header_line_number"
     */
    public function testPropertyPackageHeaderLineNumber()
    {
    }

    /**
     * Test attribute "association_agreement_id"
     */
    public function testPropertyAssociationAgreementId()
    {
    }

    /**
     * Test attribute "recurring_donation_frequency"
     */
    public function testPropertyRecurringDonationFrequency()
    {
    }

    /**
     * Test attribute "demographics"
     */
    public function testPropertyDemographics()
    {
    }

    /**
     * Test attribute "access"
     */
    public function testPropertyAccess()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "conference"
     */
    public function testPropertyConference()
    {
    }

    /**
     * Test attribute "association"
     */
    public function testPropertyAssociation()
    {
    }

    /**
     * Test attribute "gift_message"
     */
    public function testPropertyGiftMessage()
    {
    }
}
