<?php
/**
 * OrderShippingInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderShippingInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Information pertaining to shipping an order.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderShippingInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderShippingInfo"
     */
    public function testOrderShippingInfo()
    {
    }

    /**
     * Test attribute "is_return"
     */
    public function testPropertyIsReturn()
    {
    }

    /**
     * Test attribute "is_rush_ship"
     */
    public function testPropertyIsRushShip()
    {
    }

    /**
     * Test attribute "requested_ship_via_code"
     */
    public function testPropertyRequestedShipViaCode()
    {
    }

    /**
     * Test attribute "is_free_shipping"
     */
    public function testPropertyIsFreeShipping()
    {
    }

    /**
     * Test attribute "ship_date"
     */
    public function testPropertyShipDate()
    {
    }

    /**
     * Test attribute "actual_ship_date"
     */
    public function testPropertyActualShipDate()
    {
    }

    /**
     * Test attribute "is_post_shipped"
     */
    public function testPropertyIsPostShipped()
    {
    }

    /**
     * Test attribute "is_drop_shipped"
     */
    public function testPropertyIsDropShipped()
    {
    }

    /**
     * Test attribute "actual_ship_via_code"
     */
    public function testPropertyActualShipViaCode()
    {
    }

    /**
     * Test attribute "ship_through_customer_number"
     */
    public function testPropertyShipThroughCustomerNumber()
    {
    }

    /**
     * Test attribute "ship_to_count"
     */
    public function testPropertyShipToCount()
    {
    }

    /**
     * Test attribute "tracking_information"
     */
    public function testPropertyTrackingInformation()
    {
    }
}
