<?php
/**
 * OrderInvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderInvoiceTest Class Doc Comment
 *
 * @category    Class
 * @description An invoice for a customer transaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderInvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderInvoice"
     */
    public function testOrderInvoice()
    {
    }

    /**
     * Test attribute "debit_number"
     */
    public function testPropertyDebitNumber()
    {
    }

    /**
     * Test attribute "bill_to"
     */
    public function testPropertyBillTo()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "invoice_amount"
     */
    public function testPropertyInvoiceAmount()
    {
    }

    /**
     * Test attribute "amount_due"
     */
    public function testPropertyAmountDue()
    {
    }

    /**
     * Test attribute "amount_paid"
     */
    public function testPropertyAmountPaid()
    {
    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "early_payment_discount_available"
     */
    public function testPropertyEarlyPaymentDiscountAvailable()
    {
    }

    /**
     * Test attribute "early_payment_discount_date"
     */
    public function testPropertyEarlyPaymentDiscountDate()
    {
    }

    /**
     * Test attribute "installments"
     */
    public function testPropertyInstallments()
    {
    }
}
