<?php
/**
 * OrderLineSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderLineSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description The summary information for an order line.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderLineSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderLineSummary"
     */
    public function testOrderLineSummary()
    {
    }

    /**
     * Test attribute "billing_currency_code"
     */
    public function testPropertyBillingCurrencyCode()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "is_package_component"
     */
    public function testPropertyIsPackageComponent()
    {
    }

    /**
     * Test attribute "is_premium"
     */
    public function testPropertyIsPremium()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {
    }

    /**
     * Test attribute "net_discount"
     */
    public function testPropertyNetDiscount()
    {
    }

    /**
     * Test attribute "net_sales_amount"
     */
    public function testPropertyNetSalesAmount()
    {
    }

    /**
     * Test attribute "net_shipping_charges"
     */
    public function testPropertyNetShippingCharges()
    {
    }

    /**
     * Test attribute "net_tax"
     */
    public function testPropertyNetTax()
    {
    }

    /**
     * Test attribute "net_total_cost"
     */
    public function testPropertyNetTotalCost()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "package_header_line_id"
     */
    public function testPropertyPackageHeaderLineId()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "promotion_choice"
     */
    public function testPropertyPromotionChoice()
    {
    }

    /**
     * Test attribute "promotion_code"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "quantity_ordered"
     */
    public function testPropertyQuantityOrdered()
    {
    }

    /**
     * Test attribute "sales_amount_ordered"
     */
    public function testPropertySalesAmountOrdered()
    {
    }

    /**
     * Test attribute "sales_amount_shipped"
     */
    public function testPropertySalesAmountShipped()
    {
    }

    /**
     * Test attribute "shipping_charges"
     */
    public function testPropertyShippingCharges()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "total_cost"
     */
    public function testPropertyTotalCost()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "is_cancelled"
     */
    public function testPropertyIsCancelled()
    {
    }

    /**
     * Test attribute "is_association_component"
     */
    public function testPropertyIsAssociationComponent()
    {
    }

    /**
     * Test attribute "operation_code"
     */
    public function testPropertyOperationCode()
    {
    }

    /**
     * Test attribute "is_gift"
     */
    public function testPropertyIsGift()
    {
    }
}
