<?php
/**
 * QuestionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuestionTest Class Doc Comment
 *
 * @category    Class
 * @description A question to present to the user.  Several types of questions are supported.    Choose One and Choose Many questions include a list of choices.  Basic questions  can include a list of choices to use as suggested values.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuestionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Question"
     */
    public function testQuestion()
    {
    }

    /**
     * Test attribute "question_code"
     */
    public function testPropertyQuestionCode()
    {
    }

    /**
     * Test attribute "question_type"
     */
    public function testPropertyQuestionType()
    {
    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "prompt"
     */
    public function testPropertyPrompt()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "default_response"
     */
    public function testPropertyDefaultResponse()
    {
    }

    /**
     * Test attribute "choices"
     */
    public function testPropertyChoices()
    {
    }
}
