<?php
/**
 * ResponseTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseTypeTest Class Doc Comment
 *
 * @category    Class
 * @description An Advantage Response Type (or Order Source) from the CDSRST-T table
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseType"
     */
    public function testResponseType()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_on_phone"
     */
    public function testPropertyIsOnPhone()
    {
    }

    /**
     * Test attribute "is_from_web"
     */
    public function testPropertyIsFromWeb()
    {
    }

    /**
     * Test attribute "are_ftc_notices_sent"
     */
    public function testPropertyAreFtcNoticesSent()
    {
    }

    /**
     * Test attribute "is_check_payment_allowed"
     */
    public function testPropertyIsCheckPaymentAllowed()
    {
    }

    /**
     * Test attribute "is_credit_card_payment_allowed"
     */
    public function testPropertyIsCreditCardPaymentAllowed()
    {
    }

    /**
     * Test attribute "is_direct_debit_payment_allowed"
     */
    public function testPropertyIsDirectDebitPaymentAllowed()
    {
    }

    /**
     * Test attribute "is_account_credit_payment_allowed"
     */
    public function testPropertyIsAccountCreditPaymentAllowed()
    {
    }

    /**
     * Test attribute "is_miscellaneous_credit_payment_allowed"
     */
    public function testPropertyIsMiscellaneousCreditPaymentAllowed()
    {
    }

    /**
     * Test attribute "is_gift_certificate_payment_allowed"
     */
    public function testPropertyIsGiftCertificatePaymentAllowed()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "prompt_for_card_security_code"
     */
    public function testPropertyPromptForCardSecurityCode()
    {
    }
}
