<?php
/**
 * ControlGroup
 *
 * PHP version 5
 *
 * @category Class
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Advantage Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Advantage Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Advantage\Client\Model;

use \ArrayAccess;
use \Advantage\Client\ObjectSerializer;

/**
 * ControlGroup Class Doc Comment
 *
 * @category Class
 * @description Model for Control Group
 * @package  Advantage\Client
 * @author   Advantage Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ControlGroup implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ControlGroup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'date' => '\DateTime',
        'code' => 'string',
        'name' => 'string',
        'order_source_code' => 'string',
        'actual_totals' => '\Advantage\Client\Model\ControlGroupTotals',
        'expected_totals' => '\Advantage\Client\Model\ControlGroupTotals',
        'defaults' => '\Advantage\Client\Model\ControlGroupDefaults',
        'subscription_defaults' => '\Advantage\Client\Model\ControlGroupSubscriptionDefaults',
        'subscription_audit_defaults' => '\Advantage\Client\Model\ControlGroupSubscriptionAuditDefaults',
        'product_defaults' => '\Advantage\Client\Model\ControlGroupProductDefaults',
        'membership_defaults' => '\Advantage\Client\Model\ControlGroupMembershipDefaults',
        'conference_defaults' => '\Advantage\Client\Model\ControlGroupConferenceDefaults',
        'status' => '\Advantage\Client\Model\ControlGroupStatus',
        'owning_user_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'date' => 'date-time',
        'code' => null,
        'name' => null,
        'order_source_code' => null,
        'actual_totals' => null,
        'expected_totals' => null,
        'defaults' => null,
        'subscription_defaults' => null,
        'subscription_audit_defaults' => null,
        'product_defaults' => null,
        'membership_defaults' => null,
        'conference_defaults' => null,
        'status' => null,
        'owning_user_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'Date',
        'code' => 'Code',
        'name' => 'Name',
        'order_source_code' => 'OrderSourceCode',
        'actual_totals' => 'ActualTotals',
        'expected_totals' => 'ExpectedTotals',
        'defaults' => 'Defaults',
        'subscription_defaults' => 'SubscriptionDefaults',
        'subscription_audit_defaults' => 'SubscriptionAuditDefaults',
        'product_defaults' => 'ProductDefaults',
        'membership_defaults' => 'MembershipDefaults',
        'conference_defaults' => 'ConferenceDefaults',
        'status' => 'Status',
        'owning_user_code' => 'OwningUserCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
        'code' => 'setCode',
        'name' => 'setName',
        'order_source_code' => 'setOrderSourceCode',
        'actual_totals' => 'setActualTotals',
        'expected_totals' => 'setExpectedTotals',
        'defaults' => 'setDefaults',
        'subscription_defaults' => 'setSubscriptionDefaults',
        'subscription_audit_defaults' => 'setSubscriptionAuditDefaults',
        'product_defaults' => 'setProductDefaults',
        'membership_defaults' => 'setMembershipDefaults',
        'conference_defaults' => 'setConferenceDefaults',
        'status' => 'setStatus',
        'owning_user_code' => 'setOwningUserCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
        'code' => 'getCode',
        'name' => 'getName',
        'order_source_code' => 'getOrderSourceCode',
        'actual_totals' => 'getActualTotals',
        'expected_totals' => 'getExpectedTotals',
        'defaults' => 'getDefaults',
        'subscription_defaults' => 'getSubscriptionDefaults',
        'subscription_audit_defaults' => 'getSubscriptionAuditDefaults',
        'product_defaults' => 'getProductDefaults',
        'membership_defaults' => 'getMembershipDefaults',
        'conference_defaults' => 'getConferenceDefaults',
        'status' => 'getStatus',
        'owning_user_code' => 'getOwningUserCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['order_source_code'] = isset($data['order_source_code']) ? $data['order_source_code'] : null;
        $this->container['actual_totals'] = isset($data['actual_totals']) ? $data['actual_totals'] : null;
        $this->container['expected_totals'] = isset($data['expected_totals']) ? $data['expected_totals'] : null;
        $this->container['defaults'] = isset($data['defaults']) ? $data['defaults'] : null;
        $this->container['subscription_defaults'] = isset($data['subscription_defaults']) ? $data['subscription_defaults'] : null;
        $this->container['subscription_audit_defaults'] = isset($data['subscription_audit_defaults']) ? $data['subscription_audit_defaults'] : null;
        $this->container['product_defaults'] = isset($data['product_defaults']) ? $data['product_defaults'] : null;
        $this->container['membership_defaults'] = isset($data['membership_defaults']) ? $data['membership_defaults'] : null;
        $this->container['conference_defaults'] = isset($data['conference_defaults']) ? $data['conference_defaults'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['owning_user_code'] = isset($data['owning_user_code']) ? $data['owning_user_code'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date Control Group Date
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Control Group ID
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Control Group Name (Description)
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets order_source_code
     *
     * @return string
     */
    public function getOrderSourceCode()
    {
        return $this->container['order_source_code'];
    }

    /**
     * Sets order_source_code
     *
     * @param string $order_source_code Origination of this order
     *
     * @return $this
     */
    public function setOrderSourceCode($order_source_code)
    {
        $this->container['order_source_code'] = $order_source_code;

        return $this;
    }

    /**
     * Gets actual_totals
     *
     * @return \Advantage\Client\Model\ControlGroupTotals
     */
    public function getActualTotals()
    {
        return $this->container['actual_totals'];
    }

    /**
     * Sets actual_totals
     *
     * @param \Advantage\Client\Model\ControlGroupTotals $actual_totals Actual Control Totals
     *
     * @return $this
     */
    public function setActualTotals($actual_totals)
    {
        $this->container['actual_totals'] = $actual_totals;

        return $this;
    }

    /**
     * Gets expected_totals
     *
     * @return \Advantage\Client\Model\ControlGroupTotals
     */
    public function getExpectedTotals()
    {
        return $this->container['expected_totals'];
    }

    /**
     * Sets expected_totals
     *
     * @param \Advantage\Client\Model\ControlGroupTotals $expected_totals Expected Control Totals
     *
     * @return $this
     */
    public function setExpectedTotals($expected_totals)
    {
        $this->container['expected_totals'] = $expected_totals;

        return $this;
    }

    /**
     * Gets defaults
     *
     * @return \Advantage\Client\Model\ControlGroupDefaults
     */
    public function getDefaults()
    {
        return $this->container['defaults'];
    }

    /**
     * Sets defaults
     *
     * @param \Advantage\Client\Model\ControlGroupDefaults $defaults Defaults
     *
     * @return $this
     */
    public function setDefaults($defaults)
    {
        $this->container['defaults'] = $defaults;

        return $this;
    }

    /**
     * Gets subscription_defaults
     *
     * @return \Advantage\Client\Model\ControlGroupSubscriptionDefaults
     */
    public function getSubscriptionDefaults()
    {
        return $this->container['subscription_defaults'];
    }

    /**
     * Sets subscription_defaults
     *
     * @param \Advantage\Client\Model\ControlGroupSubscriptionDefaults $subscription_defaults Subscription Defaults
     *
     * @return $this
     */
    public function setSubscriptionDefaults($subscription_defaults)
    {
        $this->container['subscription_defaults'] = $subscription_defaults;

        return $this;
    }

    /**
     * Gets subscription_audit_defaults
     *
     * @return \Advantage\Client\Model\ControlGroupSubscriptionAuditDefaults
     */
    public function getSubscriptionAuditDefaults()
    {
        return $this->container['subscription_audit_defaults'];
    }

    /**
     * Sets subscription_audit_defaults
     *
     * @param \Advantage\Client\Model\ControlGroupSubscriptionAuditDefaults $subscription_audit_defaults Circulation Audit Defaults
     *
     * @return $this
     */
    public function setSubscriptionAuditDefaults($subscription_audit_defaults)
    {
        $this->container['subscription_audit_defaults'] = $subscription_audit_defaults;

        return $this;
    }

    /**
     * Gets product_defaults
     *
     * @return \Advantage\Client\Model\ControlGroupProductDefaults
     */
    public function getProductDefaults()
    {
        return $this->container['product_defaults'];
    }

    /**
     * Sets product_defaults
     *
     * @param \Advantage\Client\Model\ControlGroupProductDefaults $product_defaults Product Defaults
     *
     * @return $this
     */
    public function setProductDefaults($product_defaults)
    {
        $this->container['product_defaults'] = $product_defaults;

        return $this;
    }

    /**
     * Gets membership_defaults
     *
     * @return \Advantage\Client\Model\ControlGroupMembershipDefaults
     */
    public function getMembershipDefaults()
    {
        return $this->container['membership_defaults'];
    }

    /**
     * Sets membership_defaults
     *
     * @param \Advantage\Client\Model\ControlGroupMembershipDefaults $membership_defaults Membership Defaults
     *
     * @return $this
     */
    public function setMembershipDefaults($membership_defaults)
    {
        $this->container['membership_defaults'] = $membership_defaults;

        return $this;
    }

    /**
     * Gets conference_defaults
     *
     * @return \Advantage\Client\Model\ControlGroupConferenceDefaults
     */
    public function getConferenceDefaults()
    {
        return $this->container['conference_defaults'];
    }

    /**
     * Sets conference_defaults
     *
     * @param \Advantage\Client\Model\ControlGroupConferenceDefaults $conference_defaults Conference Defaults
     *
     * @return $this
     */
    public function setConferenceDefaults($conference_defaults)
    {
        $this->container['conference_defaults'] = $conference_defaults;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Advantage\Client\Model\ControlGroupStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Advantage\Client\Model\ControlGroupStatus $status Status Code and Name
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets owning_user_code
     *
     * @return string
     */
    public function getOwningUserCode()
    {
        return $this->container['owning_user_code'];
    }

    /**
     * Sets owning_user_code
     *
     * @param string $owning_user_code Owner user ID
     *
     * @return $this
     */
    public function setOwningUserCode($owning_user_code)
    {
        $this->container['owning_user_code'] = $owning_user_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


