<?php
/**
 * AcsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AcsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AcsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acsCreateSupportLog
     *
     * Creates a new client support log.
     *
     */
    public function testAcsCreateSupportLog()
    {
    }

    /**
     * Test case for acsCreateSupportLogComment
     *
     * Creates a new CSL comment.
     *
     */
    public function testAcsCreateSupportLogComment()
    {
    }

    /**
     * Test case for acsGetClient
     *
     * Gets client information given.
     *
     */
    public function testAcsGetClient()
    {
    }

    /**
     * Test case for acsGetClientArea
     *
     * Get an area for a client..
     *
     */
    public function testAcsGetClientArea()
    {
    }

    /**
     * Test case for acsGetClientAreas
     *
     * Get all areas for a client..
     *
     */
    public function testAcsGetClientAreas()
    {
    }

    /**
     * Test case for acsGetClientByAbbreviation
     *
     * Gets client information given.
     *
     */
    public function testAcsGetClientByAbbreviation()
    {
    }

    /**
     * Test case for acsGetClientContact
     *
     * Get information about a client contact person..
     *
     */
    public function testAcsGetClientContact()
    {
    }

    /**
     * Test case for acsGetClientContacts
     *
     * Get all contact people for a client..
     *
     */
    public function testAcsGetClientContacts()
    {
    }

    /**
     * Test case for acsGetClientJob
     *
     * Get a job for a client..
     *
     */
    public function testAcsGetClientJob()
    {
    }

    /**
     * Test case for acsGetClientJobs
     *
     * Get all jobs for a client..
     *
     */
    public function testAcsGetClientJobs()
    {
    }

    /**
     * Test case for acsGetClients
     *
     * Get all active clients..
     *
     */
    public function testAcsGetClients()
    {
    }

    /**
     * Test case for acsGetSupportLog
     *
     * Gets information about a client support log.
     *
     */
    public function testAcsGetSupportLog()
    {
    }

    /**
     * Test case for acsGetSupportLogComments
     *
     * Get all comments for a client support log.
     *
     */
    public function testAcsGetSupportLogComments()
    {
    }

    /**
     * Test case for acsSearchSupportLogs
     *
     * Get information for client support logs matching a search argument..
     *
     */
    public function testAcsSearchSupportLogs()
    {
    }
}
