<?php
/**
 * ConferenceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConferenceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConferenceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for conferenceCreateConferenceChoice
     *
     * Creates a conference choice and the sessions that will be associated with it.
     *
     */
    public function testConferenceCreateConferenceChoice()
    {
    }

    /**
     * Test case for conferenceGet
     *
     * Get information for a given conference.
     *
     */
    public function testConferenceGet()
    {
    }

    /**
     * Test case for conferenceGetChoice
     *
     * Returns a conference choice and all sessions associated with that choice code.
     *
     */
    public function testConferenceGetChoice()
    {
    }

    /**
     * Test case for conferenceGetChoices
     *
     * Returns the list of all choices associated with a conference.
     *
     */
    public function testConferenceGetChoices()
    {
    }

    /**
     * Test case for conferenceGetLocations
     *
     * Returns the list of all locations associated with a conference.
     *
     */
    public function testConferenceGetLocations()
    {
    }

    /**
     * Test case for conferenceGetSession
     *
     * Returns a conference session.
     *
     */
    public function testConferenceGetSession()
    {
    }

    /**
     * Test case for conferenceGetSessions
     *
     * Returns the list of all sessions associated with a conference.
     *
     */
    public function testConferenceGetSessions()
    {
    }

    /**
     * Test case for conferenceUpdateConferenceChoice
     *
     * Update an existing conference choice and associated sessions.
     *
     */
    public function testConferenceUpdateConferenceChoice()
    {
    }

    /**
     * Test case for conferenceUpdateConferenceLocation
     *
     * Update an existing conference location.
     *
     */
    public function testConferenceUpdateConferenceLocation()
    {
    }

    /**
     * Test case for conferenceUpdateConferenceSession
     *
     * Update an existing conference session..
     *
     */
    public function testConferenceUpdateConferenceSession()
    {
    }
}
