<?php
/**
 * ProductInventoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advantage.Rest.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductInventoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductInventoryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for productInventoryCreateInventoryAdjustment
     *
     * .
     *
     */
    public function testProductInventoryCreateInventoryAdjustment()
    {
    }

    /**
     * Test case for productInventoryCreateItemInventoryReceipt
     *
     * .
     *
     */
    public function testProductInventoryCreateItemInventoryReceipt()
    {
    }

    /**
     * Test case for productInventoryCreateItemInventoryReceipt_0
     *
     * .
     *
     */
    public function testProductInventoryCreateItemInventoryReceipt0()
    {
    }

    /**
     * Test case for productInventoryGetInventory
     *
     * Get the inventory status for a given product..
     *
     */
    public function testProductInventoryGetInventory()
    {
    }

    /**
     * Test case for productInventoryGetInventoryAdjustment
     *
     * .
     *
     */
    public function testProductInventoryGetInventoryAdjustment()
    {
    }

    /**
     * Test case for productInventoryGetItemInventoryReceipt
     *
     * .
     *
     */
    public function testProductInventoryGetItemInventoryReceipt()
    {
    }
}
